import type { Metadata } from "next";
import { Poppins } from "next/font/google";
// import "./globals.css";
import "@/public/assets/css/style.css";
import { Sidebar } from "@/components/sidebar";
import { Navbar } from "@/components/navbar";
import { Download } from "@/components/download";
import { ReduxProvider } from "@/store/reduxProvider";
import HelperScript from "@/utils/helperScript";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Shine Maung Oo",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/favicon.ico", type: "image/x-icon" },
      { url: "/favicon.png", type: "image/png" },
    ],
    shortcut: "/favicon.png",
    apple: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <HelperScript />
        <ReduxProvider>
          <main>
            <Sidebar />
            <div className="main-content">
              <Navbar />
              {children}
              <Download />
            </div>
          </main>
        </ReduxProvider>
      </body>
    </html>
  );
}
